#! /bin/sh
/bin/rm -rf ./chm
/bin/rm -rf ./config.*
/usr/bin/find src -type f \( -name '*.so' -o -name '*.o' -o -name '*.d' -o -name '*.dll' -o -name '*.a' -o -name '*.rc' \) -delete
/usr/bin/find src -type f -name 'Makedeps' -delete
/bin/rm -f -- *~ */*~ */*/*~
